from typing import TypedDict, Dict, Any, Optional


class TraceContext(TypedDict, total=False):
    """
    Shared Langfuse tracing context.

    Used across:
    - sessions
    - users
    - metadata
    - tags
    """

    session_id: str
    user_id: str
    trace_metadata: Dict[str, Any]
    tags: list[str]


class AgentState(TypedDict):
    """
    Central state shared across all analysis agents.

    This state flows through all agents and gets enriched step by step.

    Structure:
    - delivery: input data for a single ball
    - outputs: all agent outputs stored in structured format
    - trace_context: shared Langfuse observability context
    """

    # Input: single delivery (one ball data)
    delivery: Dict[str, Any]

    # Shared tracing/session context
    trace_context: TraceContext

    # Output: structured outputs from all agents
    outputs: Dict[str, Any]


def create_initial_state(
    delivery: Dict[str, Any],
    session_id: Optional[str] = None,
    user_id: Optional[str] = None,
    trace_metadata: Optional[Dict[str, Any]] = None,
    tags: Optional[list[str]] = None,
) -> AgentState:
    """
    Initialize state for one delivery.

    Args:
        delivery (dict):
            One delivery's structured data generated by the pipeline

        session_id (str):
            Langfuse session identifier

        user_id (str):
            Langfuse user identifier

        trace_metadata (dict):
            Extra metadata attached to traces

        tags (list[str]):
            Langfuse tags

    Returns:
        AgentState
    """

    return {
        "delivery": delivery,

        "trace_context": {
            "session_id": session_id,
            "user_id": user_id,
            "trace_metadata": trace_metadata or {},
            "tags": tags or [],
        },

        "outputs": {
            "commentator": {
                "bowler_analysis": {},
                "batter_analysis": {}
            },

            "batting": {
                "bowler_view": {},
                "batter_view": {}
            },

            "fielding": {
                "bowler_view": {},
                "batter_view": {}
            },

            "bowling": {
                "bowler_view": {},
                "batter_view": {}
            },

            "Biomechanics": {
                "bowler_biomechanics_analysis": {},
                "batter_biomechanics_analysis": {}

            }
        }
    }
